/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-05-04 18:57:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Đăng nhập</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"https://andrewlock.net/content/images/2016/10/icon.png\">\r\n");
      out.write("<style>\r\n");
      out.write(".bg-image-vertical {\r\n");
      out.write("position: relative;\r\n");
      out.write("overflow: hidden;\r\n");
      out.write("background-repeat: no-repeat;\r\n");
      out.write("background-position: right center;\r\n");
      out.write("background-size: auto 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".card { {\r\n");
      out.write("    margin-bottom: 2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 1025px) {\r\n");
      out.write(".h-custom-2 {\r\n");
      out.write("height: 100%;\r\n");
      out.write("}\r\n");
      out.write("}</style>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" \r\n");
      out.write("     integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\" crossorigin=\"anonymous\"> \r\n");
      out.write("     <script src=\"https://kit.fontawesome.com/ee36f81461.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<section class=\"vh-100\" style=\"background-color: #9A616D; height: 100%!important;\">\r\n");
      out.write("  <div class=\"container py-5 h-100\">\r\n");
      out.write("    <div class=\"row d-flex justify-content-center align-items-center h-100\">\r\n");
      out.write("      <div class=\"col col-xl-10\">\r\n");
      out.write("        <div class=\"card\" style=\"border-radius: 1rem;\">\r\n");
      out.write("          <div class=\"row g-0\">\r\n");
      out.write("            <div class=\"col-md-6 col-lg-5 d-none d-md-block\">\r\n");
      out.write("              <img src=\"https://watermark.lovepik.com/photo/20211208/large/lovepik-vertical-shot-vertical-screen-guilin-scenery-picture_501582051.jpg\"\r\n");
      out.write("                alt=\"login form\" class=\"img-fluid\" style=\"border-radius: 1rem 0 0 1rem;\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 col-lg-7 d-flex align-items-center\">\r\n");
      out.write("              <div class=\"card-body p-4 p-lg-5 text-black\">\r\n");
      out.write("\r\n");
      out.write("               <form action=\"login.htm\" method=\"post\">\r\n");
      out.write("                  <div class=\"d-flex align-items-center mb-3 pb-1\">\r\n");
      out.write("                    <span class=\"h1 fw-bold mb-0\">QUẢN LÝ ĐẶT TOUR DU LỊCH</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <h5 class=\"fw-normal mb-3 pb-3\" style=\"letter-spacing: 1px;\">Đăng nhập vào tài khoản của bạn</h5>\r\n");
      out.write("                 \r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-outline mb-4\">\r\n");
      out.write("                    <input type=\"text\" id=\"form2Example17\" class=\"form-control form-control-lg\" name=\"username\" />\r\n");
      out.write("                     <form:errors path=\"username\"/>\r\n");
      out.write("                    <label class=\"form-label\" for=\"form2Example17\">Tên đăng nhập</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-outline mb-4\">\r\n");
      out.write("                    <input type=\"password\" id=\"form2Example27\" class=\"form-control form-control-lg\" name=\"password\"/>\r\n");
      out.write("                    <form:errors path=\"password\"/>\r\n");
      out.write("                    <label class=\"form-label\" for=\"form2Example27\">Mật khẩu</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"pt-1 mb-4\">\r\n");
      out.write("                    <button class=\"btn btn-dark btn-lg btn-block\" >ĐĂNG NHẬP </button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <a class=\"small text-muted\" href=\"#!\">Quên mật khẩu?</a>\r\n");
      out.write("                </form>\r\n");
      out.write("				<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
